### ISSUE TITLE
PDF JIS Z 8301: 2nd ToC page header

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-jis#20]
Source issue: https://github.com/metanorma/metanorma-jis/issues/9

Original PDF contains ToC title at the end of the header:
![image](https://user-images.githubusercontent.com/5559926/227950746-b02a2867-3497-49f4-828f-957f55e928f1.png)

Generated PDF:
![image](https://user-images.githubusercontent.com/5559926/227950921-c9db1d4e-8230-4d10-b848-aae0d3bf9feb.png)

**Comment by Intelligent2013** [comment]
I've added
```xml
<fo:block><fo:marker marker-class-name="section_heading">Test</fo:marker></fo:block>
````
into `<fo:flow`
and 
```xml
<fo:retrieve-marker retrieve-class-name="section_heading" retrieve-position="first-including-carryover" retrieve-boundary="page-sequence"/>
```
in `<fo:static-content flow-name="header-even" role="artifact">`.

The IF generation causes the error
```xml
java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at org.apache.fop.render.intermediate.IFStructureTreeBuilder.replayEventsForPageSequence(IFStructureTreeBuilder.java:192)
at org.apache.fop.render.intermediate.IFSerializer.startPageSequence(IFSerializer.java:278)
```
Without IF generation, PDF renders ok.

Looks like it's Apache FOP bug. I'll investigate which workaround solution should be applied.

**Comment by Intelligent2013** [comment]
Done.
First ToC page - without the section title after docidentifier:
![image](https://user-images.githubusercontent.com/5559926/231537147-3e5c1f0c-4fe1-4546-b132-aec6d415305c.png)

2nd ToC page - with the section title after docidentifier::
![image](https://user-images.githubusercontent.com/5559926/231537255-be8fca65-a77f-439c-9aaa-a1390447c989.png)
