### ISSUE TITLE
PDF JIS Z 8301: error `undefined method `after' for nil:NilClass`

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-jis#33]
Source issue: https://github.com/metanorma/metanorma-jis/issues/9

The error occurs on the `29-tables.adoc` processing.
Stack trace:
```
Metanorma XML Syntax: (XML Line 006062:69): element "table" not allowed here; expected the element end-tag or element "dl", "figure", "formula", "note", "ol", "p", "quote", "sourcecode" or "ul"
Metanorma XML Syntax: (XML Line 006337:57): attribute "hidden" not allowed here; expected attribute "id", "normative" or "obligation"
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-jis-0.0.3/lib/isodoc/jis/presentation_xml_convert.rb:77:in `table1'
C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/isodoc-be685090471f/lib/isodoc/presentation_function/block.rb:117:in `block in table'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.10-x64-mingw-ucrt/lib/nokogiri/xml/node_set.rb:234:in `block in each'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.10-x64-mingw-ucrt/lib/nokogiri/xml/node_set.rb:233:in `upto'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.10-x64-mingw-ucrt/lib/nokogiri/xml/node_set.rb:233:in `each'
C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/isodoc-be685090471f/lib/isodoc/presentation_function/block.rb:117:in `table'
C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/metanorma-iso-ffa1e3c2ca3f/lib/isodoc/iso/presentation_xml_convert.rb:33:in `block'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-jis-0.0.3/lib/isodoc/jis/presentation_xml_convert.rb:37:in `block'
C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/isodoc-be685090471f/lib/isodoc/presentation_xml_convert.rb:31:in `conversions'
C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/isodoc-be685090471f/lib/isodoc/presentation_xml_convert.rb:21:in `convert1'
C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/metanorma-iso-ffa1e3c2ca3f/lib/isodoc/iso/presentation_xml_convert.rb:17:in `convert1'
C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/isodoc-be685090471f/lib/isodoc/convert.rb:244:in `convert'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-jis-0.0.3/lib/metanorma/jis/processor.rb:46:in `output'
C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/metanorma-5f08d960925b/lib/metanorma/compile.rb:159:in `process_output_unthreaded'
C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/metanorma-5f08d960925b/lib/metanorma/compile.rb:145:in `process_exts1'
C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/metanorma-5f08d960925b/lib/metanorma/compile.rb:119:in `process_ext'
C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/metanorma-5f08d960925b/lib/metanorma/compile.rb:107:in `block in process_exts'
C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/metanorma-5f08d960925b/lib/metanorma/compile.rb:106:in `each'
C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/metanorma-5f08d960925b/lib/metanorma/compile.rb:106:in `process_exts'
C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/metanorma-5f08d960925b/lib/metanorma/compile.rb:37:in `compile'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.6.16/lib/metanorma/cli/compiler.rb:45:in `compile_file'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.6.16/lib/metanorma/cli/compiler.rb:30:in `compile'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.6.16/lib/metanorma/cli/compiler.rb:35:in `compile'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.6.16/lib/metanorma/cli/command.rb:244:in `compile_document'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.6.16/lib/metanorma/cli/command.rb:48:in `block in compile'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.6.16/lib/metanorma/cli/command.rb:48:in `each'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.6.16/lib/metanorma/cli/command.rb:48:in `compile'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.6.16/lib/metanorma/cli.rb:34:in `start'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.6.16/exe/metanorma:25:in `block in <top (required)>'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.6.16/exe/metanorma:43:in `<top (required)>'
C:/tools/ruby31/bin/metanorma:25:in `load'
C:/tools/ruby31/bin/metanorma:25:in `<main>'
undefined method `after' for nil:NilClass

        h = node.at(ns("./thead")) || name.after("<thead> </thead>").next
                                          ^^^^^^
```

**Comment by Intelligent2013** [comment]
Error occurs for this markup:
```adoc
====
[%unnumbered]
image::fig_29.5.1_example.png[]

[cols="^.^,^.^,^.^,^.^,^.^,^.^",options="unnumbered"]
|===
.2+h| 呼び
4+h| 寸法
.2+h| 質量（参考） +
（kg）

.<| stem:[d_1] .<| stem:[d_2] .>| stem:[l_1] .>| stem:[l_2]
| S | 25 .2+| 10 | 120 | 100 | 4.5
| T | 31.5 | 145 | 125 | 5.6
| U | 40 .2+| 20 | 180 | 160 | 7.1
| V | 50 .2+| 220 .2+| 200 | 9.0
| W | 63 | 40 | 11.2

|===
====
```

**Comment by Intelligent2013** [comment]
The issue was gone as soon I've added the title:
```
.Test
[cols="^.^,^.^,^.^,^.^,^.^,^.^",options="unnumbered"]
|===
```

May be the issue relates to https://github.com/metanorma/metanorma-jis/issues/24.
@opoudjis could you check?
