### ISSUE TITLE
PDF JIS Z 8301: PDF generation failed

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-jis#76]
Error log:
```
"fo:table-header" is missing child elements. Required content model: marker* (table-row+|table-cell+) (See position 3232:623)
org.apache.fop.fo.ValidationException: "fo:table-header" is missing child elements. Required content model: marker* (table-row+|table-cell+) (See position 3232:623)
javax.xml.transform.TransformerException: org.apache.fop.fo.ValidationException: "fo:table-header" is missing child elements. Required content model: marker* (table-row+|table-cell+) (See position 3232:623)
	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:502)
	at org.metanorma.fop.PDFGenerator.generateFOPIntermediateFormat(PDFGenerator.java:742)
	at org.metanorma.fop.PDFGenerator.runFOP(PDFGenerator.java:483)
	at org.metanorma.fop.PDFGenerator.convertmn2pdf(PDFGenerator.java:445)
	at org.metanorma.fop.PDFGenerator.process(PDFGenerator.java:306)
	at org.metanorma.fop.mn2pdf.main(mn2pdf.java:345)
```

**Comment by Intelligent2013** [comment]
Wrong Presentation XML - empty `<thead> </thead>`:
```xml
<table id="_42e1f550-704c-9531-9050-db05b902a9fa" unnumbered="true">
	<thead> </thead>
	<tbody>
		<tr>
			<th valign="middle" rowspan="2" align="center">呼び</th>
			<th colspan="4" valign="middle" align="center">寸法</th>
			<th valign="middle" rowspan="2" align="center">質量（参考）<br/>
```

There XSL-FO is wrong also:
```xml
<fo:table-header> </fo:table-header>
```

Source adoc:
```adoc
====
[%unnumbered]
image::fig_29.5.1_example.png[]

[cols="^.^,^.^,^.^,^.^,^.^,^.^",options="unnumbered"]
|===
.2+h| 呼び
4+h| 寸法
.2+h| 質量（参考） +
（kg）

.<| stem:[d_1] .<| stem:[d_2] .>| stem:[l_1] .>| stem:[l_2]
| S | 25 .2+| 10 | 120 | 100 | 4.5
| T | 31.5 | 145 | 125 | 5.6
| U | 40 .2+| 20 | 180 | 160 | 7.1
| V | 50 .2+| 220 .2+| 200 | 9.0
| W | 63 | 40 | 11.2

|===
====
```

I assume that this issue relates to the https://github.com/metanorma/metanorma-jis/issues/24
This table is without title and `unnumbered`, therefore we get empty `thead`.

ping @opoudjis

**Comment by Intelligent2013** [comment]
XSLT updated for:
- prevent processing of empty `thead`
- processing for `table/p`.
